README.md, work_cycles.md
=> Document work cycles.

README.md, applications.md
=> Initial applications list

README.md, runner.md, work_cycles.md
=> Add runner documentation.

applications.md
to make it easier to read / scan
=> Formatting changes to applications page

README.md, development_practice.md
=> Add development practice.

README.md, issues.md
=> Add sudden priority documentation, issue lifecycle, and issue docs.

README.md, vacation.md
=> Add vacation policy.

applications.md
- Remove PUDL since it's been sunsetted
- Add titler-aws to list of applications
- Add iiif host name
- Add #geo slack channel
=> Update applications list

README.md, tooling.md
=> Add tooling page.

work_cycles.md
... and maintenance week is every third week
=> Clarifies that work cycles are 2 weeks

tooling.md
Create a core area of development tooling you really need. Generally add
in more links, ensure info is accurate
=> Expand and reorganize tooling page

vacation.md
This came up in the code4lib chat and I hadn't thought about spelling it
out before.
=> Add explicit information about vacation expectations.

README.md
=> Add link to pul-it-handbook

applications.md
=> Update pulfalight POs

applications.md
=> Add AbID to applications list

inclusive_language.md
=> Point inclusive language page to pul-it-handbook

admin_resources.md
=> Add link to confluence

README.md
Looking for wordsmithing (on everything but the vision text) or formatting advice here.
=> Add vision to handbook.

student_software_developers.md
We can add in previous years but we'll want to contact those students.
Don't merge without approval from the students listed here.
=> Add student developer names to our handbook

applications.md
=> Add documentation about our cloud services to applications.

README.md
=> Blockquote the vision

admin_resources.md
=> Update travel info

work_cycles.md
update DLS standup time from 3:30 eastern to 4:00 pm eastern.
=> updated standup meeting time

README.md, _config.yml, index.md
=> Use jekyll's index.md convention and make a development-y README

admin_resources.md
=> Use new confluence url

work_cycles.md
=> Add Retrospectives

admin_resources.md, vacation.md
deduplicate with the vacation page
closes #108
=> Update the admin resources site according to team discussion

communication.md
=> Add page about communication channels and norms

work_cycles.md
=> Add Team Time to work cycles.
